[package]
name = "imgcmp"
version = "0.1.0"
authors = ["Jacob Turner <jacob.turner870@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
thiserror = "1.0.24"